export const asset = {
    logoIcon : require('./icons/logoIcon.png'),
    LoginBg : require('./icons/LoginBg.png'),
    profileIcon : require('./icons/profileIcon.png'),
    lockIcon : require('./icons/lockIcon.png'),
    eyeIcon : require('./icons/eyeIcon.png'),
    appleIcon : require('./icons/appleIcon.png'),
    facebookIcon : require('./icons/facebookIcon.png'),
    googleIcon : require('./icons/googleIcon.png'),
    blackLogoIcon : require('./icons/blackLogoIcon.png'),
    lineIcon : require('./icons/lineIcon.png'),
    verificationBgImage : require('./icons/verificationBgImage.png'),
    lifeStyleSerumImage : require('./icons/GetStarted/Lifestyle_Serum2_HERO.png'),
    moisturizerSplashImage : require('./icons/GetStarted/MoisturizerSplash_HERO.png'),
    lifestyleBoxesImage : require('./icons/GetStarted/Lifestyle_Boxes.png'),
    lifeStyleCleanserImage : require('./icons/GetStarted/Lifestyle_Cleanser.png'),
    getStartedArrow : require('./icons/GetStarted/GetStartedArrow.png'),
    getStartedArrowBG : require('./icons/GetStarted/GetStartedArrowBG.png'),
    navicon : require('./icons/Home/navicon.png'),
    homeSearch : require('./icons/Home/search.png'),
    homefilter : require('./icons/Home/filter.png'),
    homeBag : require('./icons/Home/bag.png'),
    loginAlert : require('./icons/AlertBox/LoginAlertQuestionMark.png'),
    close : require('./icons/AlertBox/closeOrCross.png'),
    sliderImage1 : require('./icons/Home/SliderImage1.png'),
    backIcon: require('./icons/back.png'),
    searchExampleImage: require('./icons/renderItemExamplePic.png'),
    heartIcon: require('./icons/heartIcon.png'),
    bagIcon: require('./icons/bagIcon.png'),
    productImage: require('./icons/productImageInProductDetails.png'),
}
